### ISSUE TITLE
Add LoopIR.Point to pretty printing

### ISSUE THREAD

**Issue by yamaguchi1024** [exo-lang/exo#454]
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/exocc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/exo/main.py", line 40, in main
    library = [
              ^
  File "/opt/homebrew/lib/python3.11/site-packages/exo/main.py", line 43, in <listcomp>
    for proc in get_procs_from_module(load_user_code(mod))
                                      ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/exo/main.py", line 92, in load_user_code
    loader.exec_module(user_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/yuka/work/exo_accelerate/test.py", line 36, in <module>
    @proc
     ^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/exo/API.py", line 54, in proc
    return Procedure(parser.result())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/exo/API.py", line 175, in __init__
    proc = TypeChecker(proc).get_loopir()
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/exo/typecheck.py", line 52, in __init__
    body = self.check_stmts(proc.body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/exo/typecheck.py", line 83, in check_stmts
    stmts += self.check_single_stmt(s)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/exo/typecheck.py", line 273, in check_single_stmt
    "expected size or index type "
  File "/opt/homebrew/lib/python3.11/site-packages/exo/LoopIR_pprint.py", line 346, in __str__
    return _format_code(_print_type(self, PrintEnv()))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/exo/LoopIR_pprint.py", line 550, in _print_type
    f"idx=[{', '.join([_print_expr(w, env) for w in t.idx])}])"
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/exo/LoopIR_pprint.py", line 550, in <listcomp>
    f"idx=[{', '.join([_print_expr(w, env) for w in t.idx])}])"
                       ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/exo/LoopIR_pprint.py", line 512, in _print_expr
    assert False, f"unrecognized expr: {type(e)}"
AssertionError: unrecognized expr: <class 'abc.LoopIR.Point'>
```

**Comment by rachitnigam** [comment]
What does the expected output look like?
